native claude install, nvm for node, ruby fixes
+ bash refactoring

using nvm instead of mise because I ran into this:

    STEP 30/80: RUN bash -c "mise use --global node"
    mise node@25.8.1     [1/3] install
    mise node@25.8.1     [1/3] download node-v25.8.1-linux-arm64.tar.gz
    gpg: Signature made Wed Mar 11 09:01:13 2026 UTC
    gpg:                using EDDSA key 5BE8A3F6C8A5C01D106C0AD820B1A390B168D356
    gpg: Good signature from "Antoine du Hamel <antoine.duhamel@platformatic.dev>" [unknown]
    gpg:                 aka "Antoine du Hamel <duhamelantoine1995@gmail.com>" [unknown]
    mise node@25.8.1     [2/3] checksum node-v25.8.1-linux-arm64.tar.gz
    mise node@25.8.1     [3/3] extract node-v25.8.1-linux-arm64.tar.gz
    mise node@25.8.1     [3/3] node -v
    mise node@25.8.1     [3/3] v25.8.1
    mise node@25.8.1     [3/3] npm -v
    /workspace/.local/share/mise/installs/node/25.8.1/bin/npm: line 77: exec: node: not found
    mise ERROR ~/.local/share/mise/installs/node/25.8.1/bin/npm failed
    mise ERROR Failed to install core:node@latest: ~/.local/share/mise/installs/node/25.8.1/bin/npm exited with non-zero status: exit code 127
    mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
    Error: building at STEP "RUN bash -c "mise use --global node"": while running runtime: exit status 1